### PR TITLE
Add EntityGroups to Limits

### PR DESCRIPTION
**Pull request by aurorasmiles**
Like suggested in https://github.com/BentoBoxWorld/Limits/issues/12 we added entity groups to limits.

entitygrouplimits:
   friendly:
      limit: 2
      entities:
      - COW
      - SHEEP`

### CODE REVIEW

**Comment by Poslovitch** [comment]
I was working on an implementation for this feature. I'll review yours and I'll suggest changes if it needs some :)

Thanks for the PR :)

**Comment by tastybento** [comment]
@Poslovitch What do you think?

**Comment by aurorasmiles** [comment]
After testing a bit we changed that the in the /is limits panel, the Name of the item is just the name of the group now, and the actuall entities in this group have been moved to the description, and we added a newline after 5 entries (otherwise if you added too many mobs the name would be too big for your screen). Also updated for the latest build

**Comment by tastybento** [comment]
Thanks!

**Pull request merged**
